general:
  kafka-topic: trader-updates

incentive:
  api:
    url: http://localhost:8080/incentive

spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: midas-core
      auto-offset-reset: earliest
